### PR TITLE
FastMail: leave a note that the U2F support is not available on mobile.

### PR DESCRIPTION
**Pull request by Flameeyes**

### CODE REVIEW

**Comment by alex-nitrokey** [comment]
I suggest:

U2F is only supported on browsers, but not for mobile apps. TOTP or SMS auth needs to be used for those.

**Comment by Flameeyes** [comment]
Let me try to find a compromise for this. "on browsers" is incorrect (or was at the time of pull request) as it was not supported on Edge. (Just confirmed, it's still not supported on Edge, despite Edge supporting U2F just fine.)

**Comment by Flameeyes** [comment]
Changed phrasing.

**Comment by alex-nitrokey** [comment]
thanks

**Pull request merged**
