### PR TITLE
1Password Update + possible fixes to verify.rb

### PR DESCRIPTION
**Pull request by Pentagrade**
1Password now Supports OTP and U2F

### CODE REVIEW

**Comment by Pentagrade** [comment]
Ah forgot to add an exception.
OTP seems to be supported for free, but U2F is for paid memberships only and also appears to be exclusive to the following models of dongle: YubiKey 4 Series, YubiKey NEO, or YubiKey FIPS Series

Source: https://support.1password.com/yubikey/

**Comment by Pentagrade** [comment]
Woo, wasn't sure if I was right to edit that verify.rb file but RuboCop didn't seem to like it.
RuboCop appeared to have a problem with line 32 and 89 not having an empty line below it but it likes it now.

**Comment by oktupol** [comment]
It seems that two-factor authentication in general requires a paid membership, according to [their two-factor authentication page](https://support.1password.com/two-factor-authentication/#get-help). Furthermore, I don't think 1Password supports U2F. [Their documentation on Yubikey](https://support.1password.com/yubikey/) only describes how to use the Yubikey Authenticator app as TOTP provider

**Comment by Pentagrade** [comment]
Ah yes, I didn't really examine the Yubico Authenticator, I was planning on setting it up tonight lol.
But I did notice on the website 1Password is listed red. So I guess it's OTP enabled for members but not really U2F?

**Comment by alex-nitrokey** [comment]
Thanks for the fix of the verify.rb which was done [upstream](https://github.com/2factorauth/twofactorauth/commit/c2e809dde8c772c3912e6b8514326b37821dda41#diff-c596bf4cb40c61664ef1fd96c2e5acd2) as well.

While I prefer having exceptions when needing a paid account, I am not sure if it makes sense here. You get only a free trial account for 30 days anyway. So, having a paid account is kind of mandatory. I would suggest to remove the exception.

**Comment by Pentagrade** [comment]
Fair enough, I have removed the exception

**Comment by alex-nitrokey** [comment]
Thanks!

**Pull request merged**
