### PR TITLE
Now supporting 2FA

### PR DESCRIPTION
**Pull request by metavida**
Update 2 sites that now support 2FA:
- Rackspace
- Dyn

Unfortunately, neither currently support OTP or U2F, but they each do have some form of 2FA.

### CODE REVIEW

**Comment by jans23** [comment]
This website is about 2FA with USB dongles, not SMS.

Sent from a mobile device.

**Comment by metavida** [comment]
Hi @jans23, thanks for the feedback. I discovered the source of my confusion. It seems like there are legacy `_data/*.yml` files that do contain data like "sms: Yes", but the current website is built from the `_data/devices/*.yml` files which do _not_ have any mention of sms & only use "otp: Yes" or "u2f: Yes"

I've updated my pull request to modify the appropriate `_data/devices/*.yml` files. Does this look better?

**Comment by metavida** [comment]
I also just created #17 in hopes that it'll help future contributors avoid the confusion I encountered.

**Comment by jans23** [comment]
The point is that we have two columns only: OTP and U2F. SMS is not in scope of this website. For this purpose you may want to use the original twofactorauth website.

**Pull request closed without merging**
