### PR TITLE
Dropbox has added U2F support

### PR DESCRIPTION
**Pull request by brycied00d**
I saw it announced on https://www.yubico.com/2015/08/dropbox-adds-support-for-fido-u2f-yubikeys/ and have successfully added my own security key.

### CODE REVIEW

**Comment by brycied00d** [comment]
Here's Dropbox's own blog announcing it https://blogs.dropbox.com/dropbox/2015/08/u2f-security-keys/

**Comment by jans23** [comment]
It's done now. But for your information, this change should have been applied to _data/devices/backup.yml instead of _data/backup.yml

**Comment by brycied00d** [comment]
@jans23 I read `CONTRIBUTING.md` and didn't see any mention of the `_data/devices/` directory. Does this documentation need to be updated, and the duplicate files removed from `_data/`?

**Comment by jans23** [comment]
Thank you for pointing this out. I updated CONTRIBUTING.md accordingly. I would prefer to keep the "duplicates" in _data/ because it allows easier syncing with original twofactorauth.

**Comment by brycied00d** [comment]
Thanks for clearing that up! :smile:

**Comment by brycied00d** [comment]
@jans23 One more thing, since I don't have any other means of contacting you/the project (issues tracker is disabled, etc): Please update the Github project's "website" to point at http://www.dongleauth.info/ instead of https://twofactorauth.org

**Comment by jans23** [comment]
You are great. I changed it now. Also I activated the issue tracker. Anything else you figured to improve?

**Comment by brycied00d** [comment]
lol, nothing comes to mind right now. At least in the future I can open issues rather than tagging on a pull request. Thanks

**Pull request closed without merging**
