### PR TITLE
Updated Mint/Turbotax as Intuit has added OTP support.

### PR DESCRIPTION
**Pull request by kunickiaj**

### CODE REVIEW

**Review by eddiewebb — COMMENTED** [review]
Although mint calls this Multi-Factor auth, and it is technically 2fa by common definition ("something else you have" which can include personal information as  mint asks), I'm not sure I consider a "Yes" for a site focused on USB/token style TFA.

Just my thoughts as a user.

**Comment by jans23** [comment]
@kunickiaj The way I understand the two links is: Turbotax does support OTP (compatible to Google Authenticator!) but Mint doesn't. Right?

**Comment by kunickiaj** [comment]
Yes that's right






On Wed, Feb 8, 2017 at 3:42 PM -0600, "jans23" <notifications@github.com> wrote:












@kunickiaj The way I understand the two links is: Turbotax does support OTP (compatible to Google Authenticator!) but Mint doesn't. Right?

**Comment by jans23** [comment]
Could you update the PR accordingly, and remove Mint, please?

**Comment by techge** [comment]
Did include turbotax it by hand as I could not edit this PR and it is rather old...

**Pull request closed without merging**
