### PR TITLE
groupme: now supports TOTP

### PR DESCRIPTION
**Pull request by mathstuf**
---
See 2factorauth/twofactorauth#4097.

### CODE REVIEW

**Comment by alex-nitrokey** [comment]
groupme is currently in communication.yml and should stay there. Please adapt your PR. Furthermore, we need the `tfa:` as well as the `hardware` and `otp` tag.

**Comment by mathstuf** [comment]
> groupme is currently in communication.yml and should stay there

My addition is the only mention on the `master` branch. Is there another branch I should be targeting? I've added the `hardware` and `software` keys since I don't see `otp` mentioned anywhere else (other than a URL).

**Comment by alex-nitrokey** [comment]
Oh, okay, now I see. We are using the branch `device_authenticators` which is the default branch of the repo. I try to change the branch to `master` in future. I am sorry for the hassle.

**Comment by mathstuf** [comment]
Ah, I see. Sorry about that; I had added this as another remote to my existing 2fa.org clone and missed that fact. I'll update it later today.

**Comment by mathstuf** [comment]
Sorry about this; I got confused when going through my stuff. See the 2fa.org PR for details.

**Pull request closed without merging**
