### PR TITLE
Add u2f and otp for login.gov

### PR DESCRIPTION
**Pull request by ssgelm**
Login.gov now supports u2f and otp

### CODE REVIEW

**Comment by alex-nitrokey** [comment]
Thanks. Do you may have a link to a docu which describes and underlines the changes?

**Comment by ssgelm** [comment]
U2F: https://www.yubico.com/2017/09/first-us-e-government-services-protected-with-fido-u2f-un-phishable-security-keys/
TOTP: https://www.login.gov/help/signing-in/what-is-an-authentication-app/

**Comment by alex-nitrokey** [comment]
> U2F: https://www.yubico.com/2017/09/first-us-e-government-services-protected-with-fido-u2f-un-phishable-security-keys/

Mh, how is id.me related to the login.gov site this PR is changing?
Sorry I am just still not sure, if/how this really applies for login.gov... the website itself is not mentioning u2f.

**Comment by ssgelm** [comment]
@alex-nitrokey so afaict they don't actually have u2f support listed anywhere in their docs, however it's definitely supported.  See the following screenshot:

Login.gov U2F

**Comment by alex-nitrokey** [comment]
Okay, looks good. I just needed to make sure, as some services talk about "security keys" but don't mean a standard, but a specific one. Thanks.

**Pull request merged**
