### PR TITLE
Ensurity ThinC-AUTH Biometric Security Key provider supports U2F/FIDO2

### PR DESCRIPTION
**Pull request by psrdotcom**
Ensurity Technologies ThinC-AUTH Biometric Security Key is FIDO2 certified and Microsoft Approved provider

### CODE REVIEW

**Comment by alex-nitrokey** [comment]
Wouldn't [this link](https://www.ensurity.com/Products/ThinC) make more sense?
Can you give me a link that shows, that otp is actually supported. Couldn't find it in a hurry.

**Comment by psrdotcom** [comment]
> Wouldn't [this link](https://www.ensurity.com/Products/ThinC) make more sense?
> Can you give me a link that shows, that otp is actually supported. Couldn't find it in a hurry.
Thanks for your reply.
We are supporting OTP through our desktop tool, upon authentication, the OTP gets displayed.
We are updating the same on our website as well.

**Comment by alex-nitrokey** [comment]
> We are supporting OTP through our desktop tool, upon authentication, the OTP gets displayed.

Is the OTP calculated on the device or the desktop?

**Comment by psrdotcom** [comment]
> > We are supporting OTP through our desktop tool, upon authentication, the OTP gets displayed.
> 
> Is the OTP calculated on the device or the desktop?

OTP will be generated on the device only upon the valid user authentication and displayed on desktop tool. Because, device doesn't have in-built screen to display.

**Review by 103058167 — APPROVED** [review]
looks good, website builds properly

**Comment by jans23** [comment]
This PR has merge conflicts. Please resolve it.

**Comment by psrdotcom** [comment]
@jans23 : We have resolved the merge conflicts. Request you to approve from your end. Thanks in advance.

**Pull request merged**
