### PR TITLE
Add miicard.com to Identity Management

### PR DESCRIPTION
**Pull request by kbuley**
miicard.com supports yubikey OTP

### CODE REVIEW

**Comment by jans23** [comment]
"OTP" at dongleauth.info refers to RFC 4226 and 6238 specifically. Yubikey's proprietary OTP would be different. From your comment I understand miicard.com supports Yubikey's proprietary OTP. Please clarify.

**Comment by kbuley** [comment]
Haven't forgot about this, yubicard proprietary is supported but trying to confirm if that's the only method supported.

**Comment by kbuley** [comment]
Confirmed miicard supports both yubi-proprietary as well as Google Authenticator/Authy style OTP. Option to enable is at my.miicard.com/member, under "Choose a secure 2-Step Verification method". Can be added via QR code or cut & paste of the secret.

**Comment by jans23** [comment]
Thank you.

**Pull request merged**
