### PR TITLE
Add Nextcloud

### PR DESCRIPTION
**Pull request by rugk**
Logo has been minimized with ~SVGO~ (**Edit:** [TinyPNG](https://tinypng.com/)).

**Edit:** Fixes https://github.com/Nitrokey/dongleauth/issues/135

### CODE REVIEW

**Comment by alex-nitrokey** [comment]
thanks for the PR. This is a duplicate to #135 
As this is controversial I could imagine to add a new category called software :thinking: 
Furthermore, the icon is too large (this is why travis isn't building), please shrink it to 2500 or less bytes.

**Comment by rugk** [comment]
Okay, anyway, I've updated it for now.

As [also explained here](https://github.com/Nitrokey/dongleauth/issues/135#issuecomment-437938544) I nowhere read the criteria as "no-self-hosted software" or so and cannot really understand why upstream says they do not want to accept that.
This is just kinda "discriminating" of self-hosted (FLOSS) projects.

**Comment by rugk** [comment]
BTW, you (in contrast to upstream) **already support Mastodon**, which is also self-hosted software, so IMHO you can make it [better than upstream](https://github.com/2factorauth/twofactorauth/pull/3550) and not discriminate against self-hosted software.

**Comment by alex-nitrokey** [comment]
Unfortunately, there are still problems with this PR.

Could you please:
* keep the alphabetical order (travis fail) by putting the entry before Nimbox
* make the icon 32x32 pixel big (travis fail) (sorry that I didn't mentioned before)
* add this doc link instead https://docs.nextcloud.com/server/14/user_manual/user_2fa.html
* add `otp: Yes` and `u2f: Yes` below of `hardware: Yes`

**Comment by rugk** [comment]
So everything is done…

**Comment by alex-nitrokey** [comment]
Thanks a lot!

**Pull request merged**
