### PR TITLE
U2F support at Gandi.net

### PR DESCRIPTION
**Pull request by baloo**

### CODE REVIEW

**Comment by ghost** [comment]
Have tested their U2F support and can confirm it works.

**Comment by baloo** [comment]
Thank you, I implemented it ;)

**Comment by ghost** [comment]
Thanks very much! I've been searching for a domain provider with decent 2FA support for a long time. I'll be sure to recommend Gandi to my security-conscious colleagues.

**Comment by ghost** [comment]
On a sort-of-related note, the login screen refuses to let me log in when my password is auto-filled, I have to add a character then delete to be able to proceed. At least, this is what happens on the mobile site. Seems to be a JS-based check.

**Comment by baloo** [comment]
@Orbixx Would you mind me asking what browser and platform you use so I can try to reproduce this? What autofills the password? Is this an extension or app?

**Comment by ghost** [comment]
@baloo Android 8, default Chrome, possibility using Chrome's built-in password manager, or it could be the new Android Smart Lock credential management.

**Comment by Flameeyes** [comment]
I was about to make a pull request for the same. Is anyone from Nitrokey actually merging these pull requests at all?

**Comment by techge** [comment]
Yes, we are. But right now with a huge delay. It has high priority on my list though. We are really sorry it took so long the last time... :(

**Comment by baloo** [comment]
\o/

**Pull request merged**
