### PR TITLE
The Ohio State University

### PR DESCRIPTION
**Pull request by facorread**

### CODE REVIEW

**Comment by alex-nitrokey** [comment]
Thanks for your PR! 
Would you mind adding the support at [2factorauth/twofactorauth](https://github.com/2factorauth/twofactorauth/) as well?

More importantly: what hardware token is supported? otp? u2f? or both?

**Comment by facorread** [comment]
Hi, when I go to 2factorauth/twofactorauth and click fork, github just takes me to facorread/dongleauth ; I do not have the time to do it by hand, sorry.

**Comment by kyanar** [comment]
@facorread this is normal - nitrokey/dongleauth is itself a fork of 2factorauth/twofactorauth, so you just need to add 2factorauth/twofactorauth as a remote, checkout the branch "master", and send a pull request to that repo

**Comment by facorread** [comment]
>> I do not have the time to do it by hand, sorry.

**Comment by facorread** [comment]
> Would you mind adding the support at [2factorauth/twofactorauth](https://github.com/2factorauth/twofactorauth/) as well?

Apparently I am not able to create a simple pull request, [see here](https://github.com/2factorauth/twofactorauth/compare/master...facorread:device_authenticators).

**Pull request merged**
