### PR TITLE
Add SoloKeys to list of U2F keys.

### PR DESCRIPTION
**Pull request by timonus**
This PR adds details about [SoloKey](https://shop.solokeys.com) U2F keys to the devices page.

### CODE REVIEW

**Comment by beerisgood** [comment]
This shop use a lot tracking stuff, like Facebook:
https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fshop.solokeys.com%2F#requests

Wouldn't buy anything from them

**Comment by alex-nitrokey** [comment]
Could you add a icon, too?
Thanks!

**Comment by timonus** [comment]
@alex-nitrokey updated the pull request with that!

**Comment by alex-nitrokey** [comment]
Thanks for your effort. Unfortunately, the build does not pass the checks.
```
1. img/providers/solokey.png is not 32x32 pixels.
2. img/providers/solokey.png should not be larger than 2500 bytes. It is currently 7422 bytes.
```

**Comment by timonus** [comment]
@alex-nitrokey just updated to fix that. Also PNGCrushed all the other provider icons to make them even smaller.

**Comment by alex-nitrokey** [comment]
Thanks a lot!

**Pull request merged**
